// <auto-generated />
using System;
using MateoSantosExam1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MateoSantosExam1P.Migrations
{
    [DbContext(typeof(MateoSantosExam1PContext))]
    [Migration("20241028160947_Primera BASE")]
    partial class PrimeraBASE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MateoSantosExam1P.Models.MS_Cerveza", b =>
                {
                    b.Property<int>("MS_CervezaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MS_CervezaId"));

                    b.Property<string>("MS_CervezaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MS_CervezaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MS_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MS_Escarchada")
                        .HasColumnType("bit");

                    b.Property<decimal>("MS_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MS_CervezaId");

                    b.ToTable("MS_Cerveza");
                });
#pragma warning restore 612, 618
        }
    }
}
